version: "3.7"
services:
  web:
    image: rym
    build:
      context: .
    networks:
      - webnet

  nginx:
    image: nginx
    volumes:
      - ./mysite.templates:/etc/nginx/conf.d/mysite.templates
    networks:
      - webnet
    depends_on:
      - web
    ports:
      - "80:80"
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.templates > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  webnet:
